# Generated by Django 3.1.2 on 2020-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnviaEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.CharField(max_length=100)),
                ('para', models.CharField(max_length=100)),
                ('msg', models.TextField()),
                ('anexo', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
